Remove HammerJS and lodash dependencies
AyogoHealth/swing pull request #1
Opened 2017-02-07 23:40 UTC by evanuk

Uses $swipe instead of HammerJS.  Needed to turn Card and Stack into Angular services in order to accomplish this.

2017-02-07 23:49 UTC, dpogue commented on package.json
> +    "angular-touch": "^1.6.1",
Should probably not mix-n-match these, even if the `^` means they'll both end up being 1.6.x

2017-02-07 23:49 UTC, dpogue commented on src/utilities.js
> +  return Array.from(element.childNodes).filter(elem => elem.nodeType === 1);
Array.from isn't supported by IE11.

`element.childNodes` should be a DOMCollection, so I *think* you can do something like this
```js
Array.prototype.filter.call(element.childNodes, elem => elem.nodeType === 1)
```

2017-02-07 23:49 UTC, dpogue commented on src/Card.js
> +  return Object.assign({}, defaultConfig, config);
Might need a polyfill for this (I had one inline in AyUser where I needed it: https://github.com/AyogoHealth/ayogo-client-common/blob/master/src/user/user.ts#L50)

2017-02-07 23:50 UTC, isuda requested changes

2017-02-07 23:50 UTC, isuda commented on src/Card.js
> +  return Object.assign({}, defaultConfig, config);
Object.assign won't work in IE11.

2017-02-07 23:50 UTC, isuda commented on src/utilities.js
> +  return Array.from(element.childNodes).filter(elem => elem.nodeType === 1);
Array.from does not work in IE11

2017-02-07 23:53 UTC, evanuk commented
If its building to a dist folder it should be okay, right?

2017-02-09 22:27 UTC, dpogue commented on src/Stack.js
> +      const group = index[index.findIndex(i => element.id === i.element.id)];
`findIndex` doesn't work in IE11 either :(

2017-02-11 00:02 UTC, dpogue approved these changes

2017-02-14 17:12 UTC, merged